# Generated by Django 4.1 on 2022-08-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_minina',
            new_name='idade_minima',
        ),
    ]
